

services:

  # Serviço para a aplicação (RTech Host)
  app:
    build: .
    container_name: auth_app
    ports:
      - "3000:3000"  # Mapeia a porta do container para o host
    environment:
      DATABASE_URL: postgres://auth_user:auth_password@postgres:5432/auth_db  # URL de conexão com o banco de dados
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - auth_network
    restart: always

  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth_network

  # Serviço do MySQL
  mysql:
    image: mysql:latest
    container_name: auth_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do Adminer (Gerenciador de BD para PostgreSQL e MySQL)
  adminer:
    image: adminer
    container_name: auth_adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - auth_network
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy

  # Serviço do PgAdmin para gerenciar o PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: auth_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge

volumes:
  postgres_data:
  mysql_data: